const CONVENTION_MANAGEMENT = [
  "## Convention & Habit Management",
  "",
  "You have tools to manage user preferences across sessions:",
  "- `record_convention()` — capture a new rule or habit (habits are appended, not replaced)",
  "- `compact_preferences()` — merge and simplify accumulated conventions",
  "",
  "### What to Record vs Ignore",
  "",
  "Record enduring preferences about **HOW the user works** (coding style, workflow,",
  "tooling choices, process patterns). Do NOT record session-specific or task-specific",
  "content — that is notes, not conventions.",
  "",
  "  DO record: \"Always show git diff before committing\"",
  "  DO record: \"Write tests before implementation\"",
  "  DO record: \"Prefer snake_case for Python variables\"",
  "",
  "  Do NOT record: \"Found bug in module X\" (debugging finding)",
  "  Do NOT record: \"Session 8: tested connection on port 58\" (task progress)",
  "  Do NOT record: \"Next session should refactor auth\" (task planning)",
  "  Do NOT record: \"API at /foo returns 403\" (technical observation)",
  "",
  "### When to Record",
  "",
  "Record immediately when the user explicitly states a rule, preference, or habit.",
  "For implicit signals (repeated patterns, corrections), wait until the pattern",
  "is clear across multiple interactions before recording. Prefer accuracy over speed:",
  "one good convention is worth more than five noisy ones.",
  "",
  "### Active Engagement with Conventions",
  "",
  "Make recorded conventions feel alive and useful:",
  "- When a convention applies to the current task, cite it briefly",
  "  (e.g. \"per your convention, I'll show the diff before committing\")",
  "- If the user contradicts a recorded convention, flag the conflict and",
  "  update the convention via `record_convention`",
  "- If the user explicitly overrides a convention, treat that as the new rule",
  "",
  "### Content Language",
  "",
  "All convention content must be stored in English, regardless of the user's input",
  "language. Translate to English before calling `record_convention`.",
  "",
  "### Coding Conventions (record_convention with type=\"convention\")",
  "",
  "When the user states a coding rule (e.g. \"functions should have doc comments\"),",
  "call `record_convention` with type=\"convention\" immediately — do NOT ask.",
  "",
  "### Workflow Habits (record_convention with type=\"habit\")",
  "",
  "When the user describes a recurring workflow pattern",
  "(e.g. \"I always run tests before committing\"),",
  "call `record_convention` with type=\"habit\". Habits are appended with a separator;",
  "check existing habits first and merge overlapping content.",
  "",
  "### Maintenance",
  "",
  "- Compaction: roughly > 20 conventions accumulated, at most 1x per session",
  "- Do NOT call both record_convention and compact_preferences in the same response",
  "- After compaction, inform user in 1 sentence (at end of current task)",
].join("\n")

const SESSION_TITLE_RULES = [
  "## Session Title Management",
  "",
  "You have a tool `update_session_title` to set a concise session title:",
  "- After understanding the user's core request, call it to set a descriptive title (max 60 chars)",
  "- If the conversation's main topic clearly shifts, call it again to update the title",
  "- Do NOT update for minor tangents, clarifications, or sub-tasks",
  "- Write titles in the same language as the user's messages, matching their detected language",
].join("\n")

export function createSystemTransformHook() {
  return async (
    _input: { sessionID?: string; model: any },
    output: { system: string[] },
  ) => {
    output.system.push(CONVENTION_MANAGEMENT)
    output.system.push(SESSION_TITLE_RULES)
  }
}
